#!/usr/bin/env python3
"""Build every AI tool instruction file from the one source in instructions/.

Usage: gen_instructions.py [--check] [--root DIR]

Without flags it writes the generated files under the repo root. With
``--check`` it writes nothing, prints each file that differs from what it
would write (or is missing, or is stale), and exits 1 if there are any.

Source files:
  instructions/entry.md          the one page workflow and rules
  instructions/rules.md          the rules, placed into the entry and every guide
  instructions/references/*.md   the step by step guides

Tokens replaced in the sources: {{version}}, {{install}}, {{install_clone}},
{{guides}} (the folder the
guides live in for that tool), {{rules}} and {{guide_index}}.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

import yaml

from reelsmith.agent_install import ENTRY_FILES, GUIDES_DIR, PROJECT_GUIDES_DIR, SKILL_DIR

GENERATOR = "scripts/gen_instructions.py"
PACKAGE_FILES = "src/reelsmith/agent_files"
PLUGIN_SKILL = "skills/reelsmith"
REPOSITORY = "https://github.com/mz-real/reelsmith"
OWNER = "mz-real"

GUIDE_ORDER = (
    "interview",
    "narrate",
    "capture-web",
    "capture-mobile",
    "script-writing",
    "voice",
    "qa",
    "troubleshooting",
)

PLUGIN_DESCRIPTION = (
    "Make narrated demo videos of your app on your own machine. The AI interviews you, "
    "then reelsmith records, scripts, voices, assembles and checks the video."
)
SKILL_DESCRIPTION = (
    "Make a narrated demo video of an app, fully local, with the reelsmith CLI. "
    'Use it when the user asks to "make a demo video of my app", wants a product '
    'walkthrough or release notes video, or says "narrate this recording" about a '
    "screen recording they already have."
)
CURSOR_DESCRIPTION = (
    "Use when the user asks to make a demo video of their app or to narrate a screen "
    "recording with reelsmith."
)

# Folders the generator owns completely. Extra .md files in them are stale.
OWNED_DIRS = (
    f"{PLUGIN_SKILL}/references",
    f"{PACKAGE_FILES}/{GUIDES_DIR}",
    f"{PACKAGE_FILES}/{SKILL_DIR}/references",
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def _version(root: Path) -> str:
    data = tomllib.loads(_read(root / "pyproject.toml"))
    return str(data["project"]["version"])


REPO_URL = "git+https://github.com/mz-real/reelsmith"


def _published(root: Path) -> bool:
    """Whether the package is on PyPI yet ([tool.reelsmith] published in pyproject)."""
    data = tomllib.loads(_read(root / "pyproject.toml"))
    return bool(data.get("tool", {}).get("reelsmith", {}).get("published", False))


def install_commands(published: bool) -> tuple[str, str]:
    """The install commands the instructions show, before and after release."""
    if published:
        return "uv tool install reelsmith", 'uv tool install --python 3.12 "reelsmith[clone]"'
    return (
        f"uv tool install {REPO_URL}",
        f'uv tool install --python 3.12 "reelsmith[clone] @ {REPO_URL}"',
    )


def _banner(source: str) -> str:
    return (
        f"<!-- Generated by {GENERATOR} from {source}. "
        "Edit the source and run the generator, not this file. -->\n"
    )


def _guide_names(root: Path) -> list[str]:
    found = {path.stem for path in (root / "instructions" / "references").glob("*.md")}
    known = [name for name in GUIDE_ORDER if name in found]
    return known + sorted(found - set(known))


def _guide_summary(text: str) -> tuple[str, str]:
    """The guide title and the first sentence of its Goal section."""
    title_match = re.search(r"^# (.+)$", text, re.MULTILINE)
    goal_match = re.search(r"^## Goal\n+(.+?)(?:\n\n|\n#)", text, re.MULTILINE | re.DOTALL)
    title = title_match.group(1).strip() if title_match else "Guide"
    goal = " ".join(goal_match.group(1).split()) if goal_match else ""
    sentence = goal.split(". ")[0].rstrip(".") + "." if goal else ""
    return title, sentence


class Sources:
    """The source files, read once."""

    def __init__(self, root: Path) -> None:
        base = root / "instructions"
        self.version = _version(root)
        self.install, self.install_clone = install_commands(_published(root))
        self.entry = _read(base / "entry.md")
        self.rules = _read(base / "rules.md").strip()
        self.guides = {
            name: _read(base / "references" / f"{name}.md") for name in _guide_names(root)
        }

    def index(self, guides_dir: str) -> str:
        lines = []
        for name, text in self.guides.items():
            title, summary = _guide_summary(text)
            lines.append(f"- `{guides_dir}/{name}.md`: {title}. {summary}".rstrip())
        return "\n".join(lines)

    def render(self, text: str, guides_dir: str) -> str:
        out = text.replace("{{rules}}", self.rules)
        out = out.replace("{{guide_index}}", self.index(guides_dir))
        out = out.replace("{{guides}}", guides_dir)
        out = out.replace("{{version}}", self.version)
        out = out.replace("{{install_clone}}", self.install_clone)
        out = out.replace("{{install}}", self.install)
        return out.rstrip() + "\n"

    def entry_for(self, guides_dir: str) -> str:
        return self.render(self.entry, guides_dir)

    def guide_for(self, name: str, guides_dir: str) -> str:
        return self.render(self.guides[name], guides_dir)


def _frontmatter(fields: dict[str, object]) -> str:
    body = yaml.safe_dump(fields, sort_keys=False, allow_unicode=True, width=1000)
    return f"---\n{body}---\n"


def _skill_files(src: Sources) -> dict[str, str]:
    """SKILL.md and its references, relative to the skill folder."""
    head = _frontmatter({"name": "reelsmith", "description": SKILL_DESCRIPTION})
    files = {"SKILL.md": head + _banner("instructions/entry.md") + src.entry_for("references")}
    for name in src.guides:
        files[f"references/{name}.md"] = _banner(
            f"instructions/references/{name}.md"
        ) + src.guide_for(name, "references")
    return files


def _cursor_rule(src: Sources) -> str:
    head = f"---\ndescription: {json.dumps(CURSOR_DESCRIPTION)}\nglobs:\nalwaysApply: false\n---\n"
    return head + _banner("instructions/entry.md") + src.entry_for(PROJECT_GUIDES_DIR)


def _handover(src: Sources) -> str:
    intro = (
        "# reelsmith handover prompt\n\n"
        "Paste everything below this line into any AI coding tool. It tells the tool how to "
        "make a narrated demo video of your app with the reelsmith CLI. If your project has "
        f"no `{PROJECT_GUIDES_DIR}/` folder, the guides are included at the end of this "
        "prompt.\n\n---\n\n"
    )
    parts = [_banner("instructions/") + intro + src.entry_for(PROJECT_GUIDES_DIR)]
    for name in src.guides:
        parts.append(
            f"\n---\n\nThe guide below is `{PROJECT_GUIDES_DIR}/{name}.md`.\n\n"
            + src.guide_for(name, PROJECT_GUIDES_DIR)
        )
    return "".join(parts)


def _json(data: object) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def _plugin_files(src: Sources) -> dict[str, str]:
    plugin = {
        "name": "reelsmith",
        "version": src.version,
        "description": PLUGIN_DESCRIPTION,
        "author": {"name": OWNER, "url": f"https://github.com/{OWNER}"},
        "homepage": REPOSITORY,
        "repository": REPOSITORY,
        "license": "MIT",
        "keywords": ["demo", "video", "narration", "screen recording"],
    }
    marketplace = {
        "name": "reelsmith",
        "owner": {"name": OWNER, "url": f"https://github.com/{OWNER}"},
        "metadata": {"description": PLUGIN_DESCRIPTION, "version": src.version},
        "plugins": [
            {
                "name": "reelsmith",
                "source": "./",
                "description": PLUGIN_DESCRIPTION,
                "version": src.version,
                "author": {"name": OWNER},
                "homepage": REPOSITORY,
                "repository": REPOSITORY,
                "license": "MIT",
            }
        ],
    }
    return {
        ".claude-plugin/plugin.json": _json(plugin),
        ".claude-plugin/marketplace.json": _json(marketplace),
    }


def build(root: Path) -> dict[str, str]:
    """Every generated file, as repo relative path to text, sorted by path."""
    src = Sources(root)
    outputs: dict[str, str] = {}
    outputs.update(_plugin_files(src))
    for rel, text in _skill_files(src).items():
        outputs[f"{PLUGIN_SKILL}/{rel}"] = text
        outputs[f"{PACKAGE_FILES}/{SKILL_DIR}/{rel}"] = text
    entry = _banner("instructions/entry.md") + src.entry_for(PROJECT_GUIDES_DIR)
    for tool, (package_name, _target) in ENTRY_FILES.items():
        text = _cursor_rule(src) if tool == "cursor" else entry
        outputs[f"{PACKAGE_FILES}/{package_name}"] = text
    for name in src.guides:
        outputs[f"{PACKAGE_FILES}/{GUIDES_DIR}/{name}.md"] = _banner(
            f"instructions/references/{name}.md"
        ) + src.guide_for(name, PROJECT_GUIDES_DIR)
    outputs["prompts/HANDOVER_PROMPT.md"] = _handover(src)
    return dict(sorted(outputs.items()))


def _stale(root: Path, outputs: dict[str, str]) -> list[str]:
    stale: list[str] = []
    for folder in OWNED_DIRS:
        for path in sorted((root / folder).glob("*.md")):
            rel = path.relative_to(root).as_posix()
            if rel not in outputs:
                stale.append(rel)
    return stale


def check(root: Path) -> list[str]:
    """Paths that are missing, differ from the generator, or are stale."""
    outputs = build(root)
    drift = []
    for rel, text in outputs.items():
        path = root / rel
        if not path.is_file() or _read(path) != text:
            drift.append(rel)
    return sorted(drift + _stale(root, outputs))


def write(root: Path) -> list[str]:
    """Write every generated file that changed, remove stale ones, return the paths."""
    outputs = build(root)
    changed: list[str] = []
    for rel, text in outputs.items():
        path = root / rel
        if path.is_file() and _read(path) == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))
        changed.append(rel)
    for rel in _stale(root, outputs):
        (root / rel).unlink()
        changed.append(rel)
    return sorted(changed)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate AI tool instruction files.")
    parser.add_argument("--check", action="store_true", help="Fail if any file would change.")
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent, help="Repo root."
    )
    args = parser.parse_args(argv)
    root: Path = args.root
    if args.check:
        drift = check(root)
        for rel in drift:
            print(f"out of date: {rel}")
        if drift:
            print(f"Run: uv run python {GENERATOR}")
            return 1
        print("Generated instruction files are up to date.")
        return 0
    for rel in write(root):
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
